name: CI - Test Recommend Books

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test_recommend_books:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          pip install pandas

      - name: Run tests
        run: python -m unittest test_recommend_books.py
